---
sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=2.1.0

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-get -y install python-pip
 - sudo pip install ansible==$ANSIBLE_VERSION
 - ansible --version

script:
 - echo localhost > inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/