---
# Clean up releases
- name: UPYUN-DEV-DEPLOY | Clean up releases
  shell: ls -1dt {{ updeployment_releases_path.stdout }}/* | tail -n +{{ updeployment_keep_releases | int + 1 }} | xargs rm -rf
  when: updeployment_keep_releases > 0
