---
# Clean up releases
- name: UPYUN-DEV-DEPLOY | Clean up releases
  shell: ls -1dt {{ deploy_releases_path.stdout }}/* | tail -n +{{ deploy_keep_releases | int + 1 }} | xargs rm -rf
  when: deploy_keep_releases > 0
