---
- name: "UPYUN-DEV-DEPLOY | rsync 从 {{ deploy_rsync_src }} 同步代码到 {{ deploy_to }}"
  shell: rsync {{ deploy_rsync_extra_params }} {{ deploy_rsync_src }} {{ deploy_to }}
  args:
    chdir: "{{ deploy_to }}"
    executable: /bin/bash

- name: "UPYUN-DEV-DEPLOY | 拷贝 project 中的项目源码到 {{ deploy_release_path.stdout }}"
  command: cp -a {{ deploy_to }}/project {{ deploy_release_path.stdout }}

- name: UPYUN-DEV-DEPLOY | 删除 project 目录
  file:
    state: absent
    path: "{{ deploy_to }}/project"
