---
# Setup folders
- name: ANSISTRANO | Ensure deployment base path exists
  file:
    state: directory
    path: "{{ dest }}"

- name: ANSISTRANO | Set releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: ANSISTRANO | Set shared path
  command: echo "{{ ansistrano_deploy_to }}/shared"
  register: ansistrano_shared_path

- name: ANSISTRANO | Set tmp path
  command: echo "{{ dest }}/tmp"
  register: ansistrano_tmp

- name: ANSISTRANO | Ensure tmp path exists
  file:
    state: directory
    path: "{{ ansistrano_tmp.stdout }}"

- name: ANSISTRANO | Ensure releases folder exists
  file:
    state: directory
    path: "{{ ansistrano_releases_path.stdout }}"

- name: ANSISTRANO | Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path.stdout }}"