---
# Update code deployment step
- name: "UPYUN-DEV-DEPLOY | 生成默认的待发布版本"
  set_fact:
    ansistrano_release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: ansistrano_release_version is not defined
  delegate_to: 127.0.0.1

- name: UPYUN-DEV-DEPLOY | 设置待发布版本目录
  command: echo "{{ ansistrano_releases_path.stdout }}/{{ ansistrano_release_version }}"
  register: ansistrano_release_path

- include: "update-code/rsync.yml"

- name: "UPYUN-DEV-DEPLOY | 将待发布版本信息写入 {{ ansistrano_release_path.stdout }}/REVISION"
  copy:
    content: "{{ ansistrano_release_version }}"
    dest: "{{ ansistrano_release_path.stdout }}/REVISION"
