---
- name: ANSISTRANO | RSYNC | Get shared path (in rsync case)
  command: echo "{{ ansistrano_shared_path.stdout }}/.shared-copy"
  register: ansistrano_shared_rsync_copy_path

- name: ANSISTRANO | Ensure shared path
  file:
    state: directory
    path: "{{ ansistrano_shared_rsync_copy_path.stdout }}"

- name: ANSISTRANO | RSYNC | Rsync application files to remote shared copy
  shell: >
    rsync -vlzrtogp --progress --delete --password-file=/etc/app.pas
    --exclude=*.swp --exclude=.git --exclude=.node --exclude=scripts
    --exclude=dev --exclude=run --exclude=v8.log --exclude=fabfile.py
    --exclude=*.pyc --exclude=.dir-locals.el --exclude=.gitignore
    --exclude=.jscsrc --exclude=.jshintrc --exclude=.projectile
    --exclude=.tm_properties --exclude=README.md --exclude=gulpfile.js
    --exclude=conf/*.js --exclude=deploy --exclude=test
    --exclude=.pm2 {{ rsync_src }} {{ ansistrano_shared_rsync_copy_path.stdout }}
  args:
    chdir: "{{ ansistrano_shared_rsync_copy_path.stdout }}"
    executable: /bin/bash

- name: ANSISTRANO | RSYNC | Deploy existing code to servers
  command: cp -a {{ ansistrano_shared_rsync_copy_path.stdout }} {{ ansistrano_release_path.stdout }}
