---
- name: ANSISTRANO | RSYNC | Get shared path (in rsync case)
  command: echo "{{ ansistrano_shared_path.stdout }}/.shared-copy"
  register: ansistrano_shared_rsync_copy_path

- name: ANSISTRANO | Ensure shared path
  file:
    state: directory
    path: "{{ ansistrano_shared_rsync_copy_path.stdout }}"

- name: ANSISTRANO | RSYNC | Rsync application files to remote shared copy
  shell: >
    rsync {{ ansistrano_rsync_opts }} {{ ansistrano_rsync_src }} {{ ansistrano_shared_rsync_copy_path.stdout }}
  args:
    chdir: "{{ ansistrano_shared_rsync_copy_path.stdout }}"
    executable: /bin/bash

- name: ANSISTRANO | RSYNC | Deploy existing code to servers
  command: cp -a {{ ansistrano_shared_rsync_copy_path.stdout }} {{ ansistrano_release_path.stdout }}
